create table album_images (album_id bigint not null, id bigint generated by default as identity, media_id bigint not null, primary key (id));
create table albums (home_id bigint not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id), constraint uq_albums_home_name unique (home_id, name));
alter table if exists album_images add constraint fk_album_images_album foreign key (album_id) references albums;
alter table if exists album_images add constraint fk_album_images_media foreign key (media_id) references media;
alter table if exists albums add constraint fk_albums_home foreign key (home_id) references homes;