spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=build/generated-schema.sql

spring.flyway.enabled=false